// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {go_func} from '../models';

export function Collector(arg1:string):Promise<Array<go_func.ImagesWithThumbnails>>;

export function OpenDialogFileFullPath():Promise<string>;
