// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Collector(arg1) {
  return window['go']['main']['App']['Collector'](arg1);
}

export function OpenDialogFileFullPath() {
  return window['go']['main']['App']['OpenDialogFileFullPath']();
}
